publisher_forward_velocity_controller:
  ros__parameters:

    wait_sec_between_publish: 5
    publish_topic: "/forward_velocity_controller/commands"

    goal_names: ["vel1", "vel2", "vel3", "vel4"]
    vel1: [1.0]  # Velocidad deseada para goal 1
    vel2: [0.5]  # Velocidad deseada para goal 2
    vel3: [-0.5] # Velocidad deseada para goal 3
    vel4: [0.0]  # Velocidad deseada para goal 4
