<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="rrbot" params="prefix">

    <!-- DefiniciÃ³n de constantes para las dimensiones del robot -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="base_mass" value="0.3" /> <!-- Masa base del robot -->
    <xacro:property name="base_width" value="0.1" /> <!-- Ancho de la base del robot -->
    <xacro:property name="base_length" value="0.1" /> <!-- Longitud de la base del robot -->
    <xacro:property name="base_height" value="0.05" /> <!-- Altura de la base del robot -->
    <xacro:property name="wheel_mass" value="0.3" /> <!-- Masa de las ruedas -->
    <xacro:property name="wheel_len" value="0.020" /> <!-- Longitud de las ruedas -->
    <xacro:property name="wheel_radius" value="0.015" /> <!-- Radio de las ruedas --> 
    <xacro:property name="z_offset" value="${base_height/2}" /> <!-- Desplazamiento vertical de la base del robot -->
    
    <!-- Se define el enlace de la base del robot -->
    <link name="${prefix}base_link">
      <collision>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_width} ${base_length} ${base_height}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <box size="${base_width} ${base_length} ${base_height}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
        <inertia
          ixx="${base_mass / 12.0 * (base_length*base_length + base_height*base_height)}" ixy="0.0" ixz="0.0"
          iyy="${base_mass / 12.0 * (base_height*base_height + base_width*base_width)}" iyz="0.0"
          izz="${base_mass / 12.0 * (base_width*base_width + base_length*base_length)}"/>
      </inertial>
    </link>

    <joint name="${prefix}wheel_joint" type="continuous">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}wheel"/>
      <origin xyz="${base_width/4} -${base_width/2 + wheel_len/2 + 0.001} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.2"/>
      <limit effort="100" velocity="1.0"/>
    </joint>

    <!-- wheel Link -->
    <link name="${prefix}wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_len*wheel_len)}" ixy="0.0" ixz="0.0"
          iyy="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_len*wheel_len)}" iyz="0.0"
          izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
        </inertial>
    </link>

  </xacro:macro>

</robot>